#!/usr/bin/env node
/* eslint global-require: 0 */
/* eslint quote-props: 0 */
const path = require('path');
const safeExec = require('./utils/child-process-wrapper.js').safeExec;

function runDevelopmentNPMInstall(callback) {
  safeExec('npm install', {
    cwd: path.resolve(__dirname, '..', 'build'),
    env: process.env,
  }, callback);
}

function runElectronNPMInstall(callback) {
  safeExec('npm install', {
    cwd: path.resolve(__dirname, '..'),
    env: Object.assign(process.env, {
      'npm_config_target': '1.4.1',
      'npm_config_arch': 'x64',
      'npm_config_target_arch': 'x64',
      'npm_config_disturl': 'https://atom.io/download/atom-shell',
      'npm_config_runtime': 'electron',
      'npm_config_build_from_source': true,
    }),
  }, callback);
}

function installProResources() {
  const fs = require('fs-plus');
  const proDir = path.resolve(path.join('src', 'pro'))
  const canaryFileExists = fs.existsSync(path.join(proDir, "README.md"))
  if (!canaryFileExists) {
    console.log(`Could not find pro submodule at ${proDir}. Skipping...`)
    return;
  }

  // copy Arc Files
  fs.copySync(path.join(proDir, 'arc-N1'), '.')

  // copy Source Extensions
  fs.copySync(path.join(proDir, 'src'), 'src');

  // link Plugins
  for (const plugin of fs.readdirSync(path.join(proDir, 'packages'))) {
    const from = path.join(proDir, 'packages', plugin);
    const to = path.join(path.resolve('internal_packages'), plugin);
    try {
      if (fs.lstatSync(to)) {
        fs.unlinkSync(to);
      }
      fs.symlinkSync(from, to, 'dir');
    } catch (err) {

    }
  }
}

console.log("-- Running npm install for dev dependencies --")
runDevelopmentNPMInstall(() => {
  console.log("-- Running npm install for app / Electron dependencies --")
  runElectronNPMInstall(() => {
    console.log("-- Linking Nylas submodule resources --")
    installProResources();
  });
})
